networks:
  proxy:
    external: true

services:
  app:
    image: 'jc21/nginx-proxy-manager:2.12.6'
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    # environment:
    #   DB_MYSQL_HOST: infra-mysql
    #   DB_MYSQL_PORT: 3306
    #   DB_MYSQL_USER: 'nginx'
    #   DB_MYSQL_PASSWORD: ''
    #   DB_MYSQL_PASSWORD__FILE: ''
    #   DB_MYSQL_NAME: 'nginx'
    volumes:
      - ./data/manager:/data
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./data/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./data/nginx/www:/etc/nginx/nginx
      - ./data/nginx/mime.types:/etc/nginx/mime.types
      - ./data/nginx/scgi_params:/etc/nginx/scgi_params
      - ./data/nginx/uwsgi_params:/etc/nginx/uwsgi_params

# secrets:
#   nginx-db-password:
#     file: ./nginx-db-password
